### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by lancelakey** [pandastrike/timezone#1]
The URL I’m going to:
http://tz.pandastrike.com:3000/

The error in the browser:

TypeError: Cannot read property 'length' of undefined
   at /usr/local/timezone/app/views/timezone.jsx:94:59
   at Array.map (native)
   at /usr/local/timezone/app/views/timezone.jsx:92:20
   at Array.map (native)
   at module.exports.React.createClass.render (/usr/local/timezone/app/views/timezone.jsx:90:17)
   at ReactCompositeComponentMixin._renderValidatedComponent (/usr/local/timezone/node_modules/react/lib/ReactCompositeComponent.js:1260:34)
   at wrapper [as _renderValidatedComponent] (/usr/local/timezone/node_modules/react/lib/ReactPerf.js:50:21)
   at ReactCompositeComponentMixin.mountComponent (/usr/local/timezone/node_modules/react/lib/ReactCompositeComponent.js:802:14)
   at wrapper [as mountComponent] (/usr/local/timezone/node_modules/react/lib/ReactPerf.js:50:21)
   at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/usr/local/timezone/node_modules/react/lib/ReactMultiChild.js:195:42)

The error on the server:

[root@ip-10-196-75-42 timezone]# node ./index.js                                          
Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779
Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory
Warning: React.renderComponentToString will be deprecated in a future version. Use React.renderToString instead.
23.243.129.39 - - [10/Feb/2015:01:06:44 +0000] "GET / HTTP/1.1" 500 1067
TypeError: Cannot read property 'length' of undefined
    at /usr/local/timezone/app/views/timezone.jsx:94:59
    at Array.map (native)
    at /usr/local/timezone/app/views/timezone.jsx:92:20
    at Array.map (native)
    at module.exports.React.createClass.render (/usr/local/timezone/app/views/timezone.jsx:90:17)
    at ReactCompositeComponentMixin._renderValidatedComponent (/usr/local/timezone/node_modules/react/lib/ReactCompositeComponent.js:1260:34)
    at wrapper [as _renderValidatedComponent] (/usr/local/timezone/node_modules/react/lib/ReactPerf.js:50:21)
    at ReactCompositeComponentMixin.mountComponent (/usr/local/timezone/node_modules/react/lib/ReactCompositeComponent.js:802:14)
    at wrapper [as mountComponent] (/usr/local/timezone/node_modules/react/lib/ReactPerf.js:50:21)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/usr/local/timezone/node_modules/react/lib/ReactMultiChild.js:195:42)

**Comment by gilesbowkett** [comment]
guessing, but the error appears to be here:

https://github.com/pandastrike/timezone/blob/master/app/views/timezone.jsx#L94

and my guess is that it's trying to access an `avatar` which is `undefined`:

```javascript
var key = person.avatar.substr(person.avatar.length - 20, 20);
```

because the `TypeError` says `Cannot read property 'length' of undefined`.

so my advice is find the Avatar.

<img src="http://tvmedia.ign.com/tv/image/article/818/818284/avatar-the-last-airbender-20070906004419863-000.jpg">

**Comment by lancelakey** [comment]
Yep. Thanks!
The is app used to not crash if the avatar was undefined but now it does.

**Comment by PandaWhisperer** [comment]
Good advice @gilesbowkett :)
